name: Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Check if repository is private
        if: github.event.repository.private
        run: exit 1

      - name: Get testing library
        run: |
          set -eu
          git clone --branch main --single-branch --depth 1 \
            https://github.com/Yandex-Practicum/tests-selfmade-project-2-public.git

      - name: Run the tests
        run: bash tests-selfmade-project-2-public/run.sh

      - name: Upload layout-compare
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: layout-compare
          path: tests-selfmade-project-2-public/output.jpg
          if-no-files-found: ignore

      - name: Show test results
        if: always()
        run: bash tests-selfmade-project-2-public/result.sh
